export default {
  users: [
    {
      id: 1,
      color: 'red',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@pitstop.com.br',
      company: 'PitStop',
    },
    {
      id: 2,
      color: 'red',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@redesavi.com.br',
      company: 'Rede Savi',
    },
    {
      id: 3,
      color: 'blue',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@rzt.com.br',
      company: 'RZT',
    },
    {
      id: 4,
      color: 'red',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@gmpetro.com.br',
      company: 'GM Petro',
    },
    {
      id: 5,
      color: 'orange',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@lyra.com.br',
      company: 'Lyra',
    },
    {
      id: 6,
      color: 'blue',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@lagoazul.com.br',
      company: 'Lago Azul',
    },
    {
      id: 7,
      color: 'purple',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@campeaopetroleo.com.br',
      company: 'Campeão Petróleo',
    },
    {
      id: 8,
      color: 'yellow',
      image: '',
      name: 'Rodrigo Mattos de Souza',
      email: 'rodrigo@petroprime.com.br',
      company: 'Petro Prime',
    },
  ],
  userTemplate: {
    id: 0,
    template: true,
    color: 'grayText',
    image: '',
    name: 'Nome do cliente',
    email: 'cliente@email.com',
    company: 'Nome da empresa',
  },
};
