export default {
  cards: [
    {
      id: 1,
      color: 'blue',
      image: 'image',
      title: 'template',
      text: 'Comece um briefing a partir de um modelo pré definido',
      cta: 'começar',
      action: '/dashboard',
    },
    {
      id: 2,
      color: 'yellow',
      image: 'image',
      title: 'Novo Questionário',
      text: 'Crie um questionário personalizado do zero',
      cta: 'criar',
      action: '/dashboard/briefing/novo',
    },
    {
      id: 3,
      color: 'orange',
      image: 'image',
      title: 'briefing',
      text: 'Edite um briefing existente',
      cta: 'editar',
      action: '/dashboard',
    },
    {
      id: 4,
      color: 'green',
      image: 'image',
      title: 'tutoriais',
      text: 'Aprenda o básico sobre construção de marcas de valor com exemplo práticos',
      cta: 'aprender',
      action: '/dashboard',
    },
  ],
};
